### ISSUE TITLE
TOP mistaking ores.

### ISSUE THREAD

**Issue by quixQuery** [RenEvo/nethercore#55] opened 2017-06-12 23:27 UTC
1.10 latest version of Nether Core and The One Probe. TOP picks up redstone, and emerald ores as coal ore.

![](https://cdn.discordapp.com/attachments/298861893513379850/323964869709922304/2017-06-12_18.12.57.png)

**Comment by renevo** [comment] 2017-07-08 20:19
Thanks for the report, think this is related to another issue as well.

**Comment by renevo** [comment] 2017-07-08 20:21
Possible duplicate of #45

**Closed as completed** 2024-03-09 16:15 UTC
Labels: bug, 1.11
